#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us

  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: true

  storage:
    layout:
      name: lvm

  identity:
    hostname: bhc-ai
    username: aiuser
    password: $6$RqYP2lhZc7gqtSqF$jNkh4gpFK8Hpqnf4TiQHHiT3zWOF6Gx4fnzyFUh2A.0yCw1OhLXL4.5iWME4qSqYCP8Eab/tsPNelABgXrlbe1
    realname: svc-ai

  ssh:
    install-server: true
    allow-pw: true

  apt:
    primary:
      - arches: [amd64, i386]
        uri: http://archive.ubuntu.com/ubuntu
    security:
      - arches: [amd64, i386]
        uri: http://security.ubuntu.com/ubuntu
    sources:
      graphics-drivers:
        source: 'ppa:graphics-drivers/ppa'
        keyid: 'FCAE110B1118213C'

  packages:
    - ubuntu-desktop-minimal
    - gdm3
    - curl
    - wget
    - git
    - build-essential
    - dkms
    - linux-headers-generic
    - firefox
    - vim
    - htop
    - tree
    - unzip
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

  late-commands:
    - curtin in-target --target=/target -- apt update
    - curtin in-target --target=/target -- ubuntu-drivers autoinstall
    - curtin in-target --target=/target -- apt upgrade -y
    - curtin in-target --target=/target -- apt autoremove -y
    - curtin in-target --target=/target -- apt autoclean
    - curtin in-target --target=/target -- grub-install /dev/sda  # Adjust if needed
    - curtin in-target --target=/target -- update-grub
    - curtin in-target --target=/target -- sed -i 's/quiet splash/verbose/' /etc/default/grub
    - curtin in-target --target=/target -- update-grub

  shutdown: reboot
