#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: AI-BOB
    username: matt
    password: >-
      $6$RqYP2lhZc7gqtSqF$jNkh4gpFK8Hpqnf4TiQHHiT3zWOF6Gx4fnzyFUh2A.0yCw1OhLXL4.5iWME4qSqYCP8Eab/tsPNelABgXrlbe1
  locale: en_US
  keyboard:
    layout: us
    variant: ''
  timezone: America/Chicago
  updates: security
  storage:
    layout:
      name: direct
  late-commands:
    - curtin in-target --target=/target apt update
    - curtin in-target --target=/target apt install -y software-properties-common wget gpg
    - curtin in-target --target=/target ubuntu-drivers autoinstall
    - curtin in-target --target=/target wget -qO- https://packages.microsoft.com/keys/microsoft.as
